export const CATEGORIES = [
  { id: 'streaming', title: 'Фильмы / Сериалы / Аниме', desc: 'Онлайн, скачивание и торренты' },
  { id: 'gaming', title: 'Игры / Эмуляция', desc: 'Репаки, ROM, эмуляторы и халява' },
  { id: 'software', title: 'Софт', desc: 'Программы, утилиты, open-source' },
  { id: 'privacy', title: 'Приватность', desc: 'VPN, adblock, браузеры, безопасность' },
  { id: 'ai', title: 'Искусственный интеллект', desc: 'Чаты, генерация картинок и голоса' },
  { id: 'music', title: 'Музыка / Подкасты', desc: 'Стриминг, скачивание, радио' },
  { id: 'reading', title: 'Книги / Манга / Комиксы', desc: 'Электронные книги, манга, аудиокниги' },
  { id: 'torrent', title: 'Торренты', desc: 'Клиенты, трекеры, индексы' },
  { id: 'android', title: 'Android / iOS', desc: 'APK, моды, sideloading' },
  { id: 'education', title: 'Обучение', desc: 'Курсы, документация, материалы' },
  { id: 'tools', title: 'Инструменты', desc: 'Браузерные и системные утилиты' },
  { id: 'download', title: 'Скачивание', desc: 'Файлообменники и менеджеры загрузок' }
];

export const RESOURCES = [
  { cat: 'streaming', name: 'NEPU', desc: 'Стриминг фильмов и сериалов', url: 'https://nepu.to/', tags: ['stream'], os: ['any'] },
  { cat: 'streaming', name: 'Cineby', desc: 'Онлайн-кинотеатр с большим каталогом', url: 'https://cineby.app/', tags: ['stream'], os: ['any'] },
  { cat: 'streaming', name: 'Aether', desc: 'Стриминг фильмов и сериалов', url: 'https://aether.mom/', tags: ['stream'], os: ['any'] },
  { cat: 'streaming', name: 'Vidsrc', desc: 'Встраиваемые источники видео', url: 'https://vidsrc.to/', tags: ['stream'], os: ['any'] },
  { cat: 'streaming', name: 'Miruro', desc: 'Стриминг аниме', url: 'https://www.miruro.com/', tags: ['stream', 'anime'], os: ['any'] },
  { cat: 'streaming', name: 'animepahe', desc: 'Аниме в хорошем качестве', url: 'https://animepahe.ru/', tags: ['stream', 'anime'], os: ['any'] },
  { cat: 'streaming', name: 'AllManga', desc: 'Аниме и манга', url: 'https://allmanga.to/', tags: ['stream', 'anime'], os: ['any'] },
  { cat: 'streaming', name: 'HiAnime', desc: 'Каталог аниме онлайн', url: 'https://hianime.to/', tags: ['stream', 'anime'], os: ['any'] },
  { cat: 'streaming', name: '1337x', desc: 'Торрент-индекс, раздел Movies', url: 'https://1337x.to/', tags: ['torrent'], os: ['any'] },
  { cat: 'streaming', name: 'Ext.to', desc: 'Торрент-поиск по категориям', url: 'https://ext.to/', tags: ['torrent'], os: ['any'] },
  { cat: 'streaming', name: 'Nyaa', desc: 'Главный торрент-трекер аниме', url: 'https://nyaa.si/', tags: ['torrent', 'anime'], os: ['any'] },
  { cat: 'streaming', name: 'Simkl', desc: 'Трекинг сериалов и аниме', url: 'https://simkl.com/', tags: ['track'], os: ['any'] },
  { cat: 'streaming', name: 'Letterboxd', desc: 'Трекинг и отзывы на фильмы', url: 'https://letterboxd.com/', tags: ['track'], os: ['any'] },
  { cat: 'streaming', name: 'MyAnimeList', desc: 'Трекинг аниме и манги', url: 'https://myanimelist.net/', tags: ['track', 'anime'], os: ['any'] },
  { cat: 'streaming', name: 'AniList', desc: 'Современный трекер аниме и манги', url: 'https://anilist.co/', tags: ['track', 'anime'], os: ['any'] },
  { cat: 'streaming', name: 'Кинопоиск', desc: 'Легальный раздел с бесплатным контентом', url: 'https://www.kinopoisk.ru/', tags: ['stream', 'ru', 'legal'], os: ['any'] },
  { cat: 'streaming', name: 'Internet Archive Movies', desc: 'Фильмы в общественном достоянии', url: 'https://archive.org/details/movies', tags: ['download', 'legal'], os: ['any'] },
  { cat: 'streaming', name: 'Soap2Day style indexes', desc: 'Индекс стриминговых зеркал FMHY-секции', url: 'https://fmhy.net/video', tags: ['index'], os: ['any'] },

  { cat: 'gaming', name: 'SteamRIP', desc: 'Предустановленные игры без Steam', url: 'https://steamrip.com/', tags: ['download'], os: ['w'] },
  { cat: 'gaming', name: 'FitGirl Repacks', desc: 'Сжатые репаки игр', url: 'https://fitgirl-repacks.site/', tags: ['download'], os: ['w'] },
  { cat: 'gaming', name: 'AnkerGames', desc: 'Каталог игр для скачивания', url: 'https://ankergames.net/', tags: ['download'], os: ['w'] },
  { cat: 'gaming', name: 'Ovagames', desc: 'Репаки и полный дистрибутив', url: 'https://ovagames.com/', tags: ['download'], os: ['w'] },
  { cat: 'gaming', name: 'GOG Games', desc: 'DRM-free игры с GOG', url: 'https://gog-games.to/', tags: ['download'], os: ['w', 'm', 'l'] },
  { cat: 'gaming', name: 'Online-Fix', desc: 'Фиксы мультиплеера для offline-игр', url: 'https://online-fix.me/', tags: ['download'], os: ['w'] },
  { cat: 'gaming', name: 'Emulation Wiki', desc: 'Гайды по эмуляторам всех платформ', url: 'https://emulation.gametechwiki.com/', tags: ['emu'], os: ['any'] },
  { cat: 'gaming', name: 'r/ROMs Mega', desc: 'Каталог ROM и ISO', url: 'https://r-roms.github.io/', tags: ['emu', 'rom'], os: ['any'] },
  { cat: 'gaming', name: "Vimm's Lair", desc: 'Классические ROM и ISO', url: 'https://vimm.net/', tags: ['emu', 'rom'], os: ['any'] },
  { cat: 'gaming', name: 'CDRomance', desc: 'PS1/PS2 и ретро-игры', url: 'https://cdromance.com/', tags: ['emu', 'rom'], os: ['any'] },
  { cat: 'gaming', name: 'Myrient', desc: 'Большой архив образов', url: 'https://myrient.erista.me/', tags: ['emu', 'rom'], os: ['any'] },
  { cat: 'gaming', name: 'Epic Games Free', desc: 'Халява недели от Epic', url: 'https://store.epicgames.com/free-games', tags: ['legal', 'free'], os: ['w', 'm'] },
  { cat: 'gaming', name: 'CS2', desc: 'Counter-Strike 2 бесплатно в Steam', url: 'https://store.steampowered.com/app/730/', tags: ['legal', 'free'], os: ['w', 'm', 'l'] },
  { cat: 'gaming', name: 'Dota 2', desc: 'Бесплатная MOBA', url: 'https://store.steampowered.com/app/570/', tags: ['legal', 'free'], os: ['w', 'm', 'l'] },
  { cat: 'gaming', name: 'Warframe', desc: 'Кооперативный шутер F2P', url: 'https://www.warframe.com/', tags: ['legal', 'free'], os: ['w'] },
  { cat: 'gaming', name: 'Path of Exile', desc: 'ARPG с честной F2P-моделью', url: 'https://www.pathofexile.com/', tags: ['legal', 'free'], os: ['w', 'm'] },
  { cat: 'gaming', name: '0 A.D.', desc: 'Открытая стратегия', url: 'https://play0ad.com/', tags: ['legal', 'os'], os: ['w', 'm', 'l'] },
  { cat: 'gaming', name: 'Minetest', desc: 'Открытый аналог Minecraft', url: 'https://www.minetest.net/', tags: ['legal', 'os'], os: ['w', 'm', 'l', 'a'] },
  { cat: 'gaming', name: 'SuperTuxKart', desc: 'Открытые аркадные гонки', url: 'https://supertuxkart.net/', tags: ['legal', 'os'], os: ['w', 'm', 'l', 'a'] },
  { cat: 'gaming', name: 'Backloggd', desc: 'Трекинг игрового бэклога', url: 'https://www.backloggd.com/', tags: ['track'], os: ['any'] },

  { cat: 'software', name: 'DaVinci Resolve', desc: 'Профессиональный монтаж, бесплатная версия', url: 'https://www.blackmagicdesign.com/products/davinciresolve', tags: ['legal', 'video'], os: ['w', 'm', 'l'] },
  { cat: 'software', name: 'Blender', desc: '3D, анимация и рендер', url: 'https://www.blender.org/', tags: ['legal', 'os'], os: ['w', 'm', 'l'] },
  { cat: 'software', name: 'GIMP', desc: 'Редактор изображений', url: 'https://www.gimp.org/', tags: ['legal', 'os'], os: ['w', 'm', 'l'] },
  { cat: 'software', name: 'Krita', desc: 'Цифровая живопись', url: 'https://krita.org/', tags: ['legal', 'os'], os: ['w', 'm', 'l'] },
  { cat: 'software', name: 'Audacity', desc: 'Запись и монтаж звука', url: 'https://www.audacityteam.org/', tags: ['legal', 'os'], os: ['w', 'm', 'l'] },
  { cat: 'software', name: 'OBS Studio', desc: 'Запись экрана и стриминг', url: 'https://obsproject.com/', tags: ['legal', 'os'], os: ['w', 'm', 'l'] },
  { cat: 'software', name: 'VLC', desc: 'Плеер любого формата', url: 'https://www.videolan.org/', tags: ['legal', 'os'], os: ['w', 'm', 'l', 'a', 'i'] },
  { cat: 'software', name: 'LibreOffice', desc: 'Офисный пакет', url: 'https://www.libreoffice.org/', tags: ['legal', 'os'], os: ['w', 'm', 'l'] },
  { cat: 'software', name: '7-Zip', desc: 'Архиватор', url: 'https://www.7-zip.org/', tags: ['legal', 'os'], os: ['w'] },
  { cat: 'software', name: 'PeaZip', desc: 'Кроссплатформенный архиватор', url: 'https://peazip.github.io/', tags: ['legal', 'os'], os: ['w', 'l'] },
  { cat: 'software', name: 'VS Code', desc: 'Редактор кода', url: 'https://code.visualstudio.com/', tags: ['legal'], os: ['w', 'm', 'l'] },
  { cat: 'software', name: 'ShareX', desc: 'Скриншоты и запись экрана', url: 'https://getsharex.com/', tags: ['legal', 'os'], os: ['w'] },
  { cat: 'software', name: 'Everything', desc: 'Мгновенный поиск файлов в Windows', url: 'https://www.voidtools.com/', tags: ['legal'], os: ['w'] },
  { cat: 'software', name: 'Massgrave', desc: 'Активация Windows и Office', url: 'https://massgrave.dev/', tags: ['tools'], os: ['w'] },
  { cat: 'software', name: 'Rufus', desc: 'Загрузочные USB', url: 'https://rufus.ie/', tags: ['legal', 'os'], os: ['w'] },
  { cat: 'software', name: 'Ventoy', desc: 'Мультизагрузочная флешка', url: 'https://www.ventoy.net/', tags: ['legal', 'os'], os: ['w', 'l'] },
  { cat: 'software', name: 'Balena Etcher', desc: 'Запись образов на USB', url: 'https://etcher.balena.io/', tags: ['legal'], os: ['w', 'm', 'l'] },
  { cat: 'software', name: 'HandBrake', desc: 'Конвертер видео', url: 'https://handbrake.fr/', tags: ['legal', 'os'], os: ['w', 'm', 'l'] },
  { cat: 'software', name: 'MPV', desc: 'Минималистичный видеоплеер', url: 'https://mpv.io/', tags: ['legal', 'os'], os: ['w', 'm', 'l'] },
  { cat: 'software', name: 'Notepad++', desc: 'Быстрый текстовый редактор', url: 'https://notepad-plus-plus.org/', tags: ['legal', 'os'], os: ['w'] },
  { cat: 'software', name: 'PowerToys', desc: 'Утилиты для Windows', url: 'https://learn.microsoft.com/windows/powertoys/', tags: ['legal'], os: ['w'] },

  { cat: 'privacy', name: 'uBlock Origin', desc: 'Блокировщик рекламы', url: 'https://ublockorigin.com/', tags: ['adblock', 'legal'], os: ['any'] },
  { cat: 'privacy', name: 'Privacy Guides', desc: 'Гайды по приватности', url: 'https://www.privacyguides.org/', tags: ['guide', 'legal'], os: ['any'] },
  { cat: 'privacy', name: 'Proton Mail', desc: 'Зашифрованная почта', url: 'https://proton.me/mail', tags: ['legal'], os: ['any'] },
  { cat: 'privacy', name: 'Proton VPN', desc: 'VPN с бесплатным тарифом', url: 'https://proton.me/vpn', tags: ['vpn', 'legal'], os: ['w', 'm', 'l', 'a', 'i'] },
  { cat: 'privacy', name: 'Mullvad VPN', desc: 'Приватный VPN без аккаунта', url: 'https://mullvad.net/', tags: ['vpn', 'legal'], os: ['w', 'm', 'l', 'a', 'i'] },
  { cat: 'privacy', name: 'IVPN', desc: 'Платный приватный VPN', url: 'https://www.ivpn.net/', tags: ['vpn', 'legal'], os: ['w', 'm', 'l', 'a', 'i'] },
  { cat: 'privacy', name: 'Firefox', desc: 'Браузер с сильной приватностью', url: 'https://www.mozilla.org/firefox/', tags: ['browser', 'legal'], os: ['w', 'm', 'l', 'a'] },
  { cat: 'privacy', name: 'Brave', desc: 'Chromium с блокировкой трекеров', url: 'https://brave.com/', tags: ['browser', 'legal'], os: ['w', 'm', 'l', 'a', 'i'] },
  { cat: 'privacy', name: 'Librewolf', desc: 'Firefox под приватность', url: 'https://librewolf.net/', tags: ['browser', 'legal'], os: ['w', 'm', 'l'] },
  { cat: 'privacy', name: 'Mullvad Browser', desc: 'Браузер от Mullvad и Tor Project', url: 'https://mullvad.net/browser', tags: ['browser', 'legal'], os: ['w', 'm', 'l'] },
  { cat: 'privacy', name: 'SearXNG', desc: 'Метапоиск без слежки', url: 'https://searx.space/', tags: ['search', 'legal'], os: ['any'] },
  { cat: 'privacy', name: 'DuckDuckGo', desc: 'Поиск без персонализации', url: 'https://duckduckgo.com/', tags: ['search', 'legal'], os: ['any'] },
  { cat: 'privacy', name: 'Have I Been Pwned', desc: 'Проверка утечек паролей и почты', url: 'https://haveibeenpwned.com/', tags: ['security', 'legal'], os: ['any'] },
  { cat: 'privacy', name: 'VirusTotal', desc: 'Проверка файлов на вирусы', url: 'https://www.virustotal.com/', tags: ['security', 'legal'], os: ['any'] },
  { cat: 'privacy', name: 'Tria.ge', desc: 'Песочница для анализа файлов', url: 'https://tria.ge/', tags: ['security', 'legal'], os: ['any'] },
  { cat: 'privacy', name: 'Bitwarden', desc: 'Менеджер паролей', url: 'https://bitwarden.com/', tags: ['security', 'legal'], os: ['any'] },
  { cat: 'privacy', name: 'KeePassXC', desc: 'Локальный менеджер паролей', url: 'https://keepassxc.org/', tags: ['security', 'os'], os: ['w', 'm', 'l'] },
  { cat: 'privacy', name: 'Tor Browser', desc: 'Анонимный браузер', url: 'https://www.torproject.org/', tags: ['browser', 'legal'], os: ['w', 'm', 'l', 'a'] },
  { cat: 'privacy', name: 'SimpleLogin', desc: 'Email-алиасы', url: 'https://simplelogin.io/', tags: ['legal'], os: ['any'] },
  { cat: 'privacy', name: 'ClearURLs', desc: 'Удаление трекеров из ссылок', url: 'https://docs.clearurls.xyz/', tags: ['extension', 'legal'], os: ['any'] },

  { cat: 'ai', name: 'ChatGPT', desc: 'ИИ-чат, есть бесплатный тариф', url: 'https://chatgpt.com/', tags: ['chat'], os: ['any'] },
  { cat: 'ai', name: 'DeepSeek', desc: 'Сильный бесплатный ИИ, хорош в коде', url: 'https://chat.deepseek.com/', tags: ['chat'], os: ['any'] },
  { cat: 'ai', name: 'GigaChat', desc: 'ИИ от Сбера', url: 'https://giga.chat/', tags: ['chat', 'ru'], os: ['any'] },
  { cat: 'ai', name: 'YandexGPT', desc: 'ИИ от Яндекса', url: 'https://alice.yandex.ru/', tags: ['chat', 'ru'], os: ['any'] },
  { cat: 'ai', name: 'Claude', desc: 'ИИ от Anthropic', url: 'https://claude.ai/', tags: ['chat'], os: ['any'] },
  { cat: 'ai', name: 'Gemini', desc: 'ИИ от Google', url: 'https://gemini.google.com/', tags: ['chat'], os: ['any'] },
  { cat: 'ai', name: 'Perplexity', desc: 'ИИ-поиск с источниками', url: 'https://www.perplexity.ai/', tags: ['chat', 'search'], os: ['any'] },
  { cat: 'ai', name: 'Kandinsky', desc: 'Генерация картинок по-русски', url: 'https://fusionbrain.ai/', tags: ['image', 'ru'], os: ['any'] },
  { cat: 'ai', name: 'Stable Diffusion', desc: 'Открытая генерация изображений', url: 'https://stability.ai/', tags: ['image', 'os'], os: ['w', 'm', 'l'] },
  { cat: 'ai', name: 'Fooocus', desc: 'Локальная генерация картинок', url: 'https://github.com/lllyasviel/Fooocus', tags: ['image', 'os'], os: ['w', 'm', 'l'] },
  { cat: 'ai', name: 'ComfyUI', desc: 'Нодовый интерфейс для генерации', url: 'https://github.com/comfyanonymous/ComfyUI', tags: ['image', 'os'], os: ['w', 'm', 'l'] },
  { cat: 'ai', name: 'Suno', desc: 'Генерация музыки по тексту', url: 'https://suno.com/', tags: ['audio'], os: ['any'] },
  { cat: 'ai', name: 'Udio', desc: 'Генерация песен', url: 'https://www.udio.com/', tags: ['audio'], os: ['any'] },
  { cat: 'ai', name: 'Hugging Face', desc: 'Каталог открытых моделей', url: 'https://huggingface.co/', tags: ['os'], os: ['any'] },
  { cat: 'ai', name: 'Ollama', desc: 'Локальный запуск LLM', url: 'https://ollama.com/', tags: ['os', 'chat'], os: ['w', 'm', 'l'] },
  { cat: 'ai', name: 'LM Studio', desc: 'GUI для локальных моделей', url: 'https://lmstudio.ai/', tags: ['chat'], os: ['w', 'm', 'l'] },
  { cat: 'ai', name: 'Open WebUI', desc: 'Веб-интерфейс для локальных LLM', url: 'https://openwebui.com/', tags: ['chat', 'os'], os: ['w', 'm', 'l'] },

  { cat: 'music', name: 'lucida', desc: 'Скачивание треков в высоком качестве', url: 'https://lucida.to/', tags: ['download'], os: ['any'] },
  { cat: 'music', name: 'squid.wtf', desc: 'Скачивание музыки', url: 'https://squid.wtf/', tags: ['download'], os: ['any'] },
  { cat: 'music', name: 'Nicotine+', desc: 'Soulseek-клиент', url: 'https://nicotine-plus.org/', tags: ['p2p', 'os'], os: ['w', 'm', 'l'] },
  { cat: 'music', name: 'Soulseek', desc: 'P2P-обмен музыкой', url: 'https://www.slsknet.org/', tags: ['p2p'], os: ['w', 'm'] },
  { cat: 'music', name: 'SpotX', desc: 'Модификация Spotify для Windows', url: 'https://github.com/SpotX-Official/SpotX', tags: ['mod'], os: ['w'] },
  { cat: 'music', name: 'Internet Archive Audio', desc: 'Большой аудиоархив', url: 'https://archive.org/details/audio', tags: ['legal', 'download'], os: ['any'] },
  { cat: 'music', name: 'Free Music Archive', desc: 'Свободная музыка', url: 'https://freemusicarchive.org/', tags: ['legal'], os: ['any'] },
  { cat: 'music', name: 'Radio Browser', desc: 'Каталог интернет-радио', url: 'https://www.radio-browser.info/', tags: ['radio', 'legal'], os: ['any'] },
  { cat: 'music', name: 'Last.fm', desc: 'Скробблинг и рекомендации', url: 'https://www.last.fm/', tags: ['track'], os: ['any'] },
  { cat: 'music', name: 'RateYourMusic', desc: 'Рейтинги альбомов', url: 'https://rateyourmusic.com/', tags: ['track'], os: ['any'] },
  { cat: 'music', name: 'Bandcamp', desc: 'Инди-музыка, часто бесплатные релизы', url: 'https://bandcamp.com/', tags: ['legal'], os: ['any'] },
  { cat: 'music', name: 'SoundCloud', desc: 'Стриминг и открытие артистов', url: 'https://soundcloud.com/', tags: ['stream'], os: ['any'] },
  { cat: 'music', name: 'Funkwhale', desc: 'Федеративный музыкальный сервис', url: 'https://funkwhale.audio/', tags: ['stream', 'os'], os: ['any'] },

  { cat: 'reading', name: "Anna's Archive", desc: 'Крупный библиотечный индекс', url: 'https://annas-archive.org/', tags: ['books'], os: ['any'] },
  { cat: 'reading', name: 'Z-Library', desc: 'Электронные книги', url: 'https://z-lib.gd/', tags: ['books'], os: ['any'] },
  { cat: 'reading', name: 'Library Genesis', desc: 'Научные и художественные книги', url: 'https://libgen.is/', tags: ['books'], os: ['any'] },
  { cat: 'reading', name: 'Sci-Hub', desc: 'Научные статьи', url: 'https://sci-hub.se/', tags: ['science'], os: ['any'] },
  { cat: 'reading', name: 'Project Gutenberg', desc: 'Книги в общественном достоянии', url: 'https://www.gutenberg.org/', tags: ['legal', 'books'], os: ['any'] },
  { cat: 'reading', name: 'Standard Ebooks', desc: 'Бесплатные книги с аккуратной вёрсткой', url: 'https://standardebooks.org/', tags: ['legal'], os: ['any'] },
  { cat: 'reading', name: 'Weeb Central', desc: 'Чтение манги', url: 'https://weebcentral.com/', tags: ['manga'], os: ['any'] },
  { cat: 'reading', name: 'MangaDex', desc: 'Каталог манги от сообщества', url: 'https://mangadex.org/', tags: ['manga'], os: ['any'] },
  { cat: 'reading', name: 'GetComics', desc: 'Комиксы', url: 'https://getcomics.org/', tags: ['comics'], os: ['any'] },
  { cat: 'reading', name: 'Readcomiconline', desc: 'Онлайн-комиксы', url: 'https://readcomiconline.li/', tags: ['comics'], os: ['any'] },
  { cat: 'reading', name: 'Audiobook Bay', desc: 'Аудиокниги', url: 'https://audiobookbay.lu/', tags: ['audio'], os: ['any'] },
  { cat: 'reading', name: 'Koodo Reader', desc: 'Кроссплатформенная читалка', url: 'https://www.koodoreader.com/', tags: ['app', 'os'], os: ['w', 'm', 'l'] },
  { cat: 'reading', name: 'Librera', desc: 'Читалка для Android', url: 'https://librera.mobi/', tags: ['app'], os: ['a'] },
  { cat: 'reading', name: 'StoryGraph', desc: 'Трекинг книг', url: 'https://thestorygraph.com/', tags: ['track'], os: ['any'] },
  { cat: 'reading', name: 'FOCAL', desc: 'Поиск книг и статей', url: 'https://focal.fmhy.net/', tags: ['index'], os: ['any'] },

  { cat: 'torrent', name: 'qBittorrent', desc: 'Открытый торрент-клиент', url: 'https://www.qbittorrent.org/', tags: ['client', 'os'], os: ['w', 'm', 'l'] },
  { cat: 'torrent', name: 'Transmission', desc: 'Лёгкий торрент-клиент', url: 'https://transmissionbt.com/', tags: ['client', 'os'], os: ['w', 'm', 'l'] },
  { cat: 'torrent', name: 'Deluge', desc: 'Торрент-клиент с плагинами', url: 'https://deluge-torrent.org/', tags: ['client', 'os'], os: ['w', 'm', 'l'] },
  { cat: 'torrent', name: 'BiglyBT', desc: 'Продвинутый клиент на базе Vuze', url: 'https://www.biglybt.com/', tags: ['client'], os: ['w', 'm', 'l'] },
  { cat: 'torrent', name: '1337x', desc: 'Популярный торрент-индекс', url: 'https://1337x.to/', tags: ['index'], os: ['any'] },
  { cat: 'torrent', name: 'RuTor', desc: 'Русскоязычный торрент-трекер', url: 'https://rutor.info/', tags: ['index', 'ru'], os: ['any'] },
  { cat: 'torrent', name: 'RuTracker', desc: 'Крупный русскоязычный трекер', url: 'https://rutracker.org/', tags: ['index', 'ru'], os: ['any'] },
  { cat: 'torrent', name: 'Nyaa', desc: 'Аниме-торренты', url: 'https://nyaa.si/', tags: ['index', 'anime'], os: ['any'] },
  { cat: 'torrent', name: 'TorrentGalaxy', desc: 'Торрент-индекс', url: 'https://torrentgalaxy.to/', tags: ['index'], os: ['any'] },
  { cat: 'torrent', name: 'YTS', desc: 'Фильмы в компактном размере', url: 'https://yts.mx/', tags: ['index'], os: ['any'] },
  { cat: 'torrent', name: 'The Pirate Bay', desc: 'Классический торрент-индекс', url: 'https://thepiratebay.org/', tags: ['index'], os: ['any'] },
  { cat: 'torrent', name: 'Torrentio', desc: 'Addon-индекс для стриминга через debrid', url: 'https://torrentio.strem.fun/', tags: ['index'], os: ['any'] },

  { cat: 'android', name: 'APKMirror', desc: 'Чистые APK без модов', url: 'https://www.apkmirror.com/', tags: ['apk', 'legal'], os: ['a'] },
  { cat: 'android', name: 'F-Droid', desc: 'Каталог open-source Android-приложений', url: 'https://f-droid.org/', tags: ['apk', 'os'], os: ['a'] },
  { cat: 'android', name: 'Droid-ify', desc: 'Современный клиент F-Droid', url: 'https://github.com/Droid-ify/client', tags: ['apk', 'os'], os: ['a'] },
  { cat: 'android', name: 'Obtainium', desc: 'Обновления приложений с GitHub и сайтов', url: 'https://github.com/ImranR98/Obtainium', tags: ['tool', 'os'], os: ['a'] },
  { cat: 'android', name: 'Mobilism', desc: 'Моды APK и форум', url: 'https://forum.mobilism.org/', tags: ['apk', 'mod'], os: ['a'] },
  { cat: 'android', name: 'Aurora Store', desc: 'Клиент Google Play без аккаунта Google', url: 'https://auroraoss.com/', tags: ['apk', 'os'], os: ['a'] },
  { cat: 'android', name: 'NewPipe', desc: 'YouTube-клиент без рекламы', url: 'https://newpipe.net/', tags: ['app', 'os'], os: ['a'] },
  { cat: 'android', name: 'Revanced', desc: 'Патчи для YouTube и других приложений', url: 'https://revanced.app/', tags: ['mod'], os: ['a'] },
  { cat: 'android', name: 'SideStore', desc: 'Sideloading на iOS без джейлбрейка', url: 'https://sidestore.io/', tags: ['ios'], os: ['i'] },
  { cat: 'android', name: 'TrollStore', desc: 'Постоянный sideload на части iOS', url: 'https://github.com/opa334/TrollStore', tags: ['ios'], os: ['i'] },
  { cat: 'android', name: 'Sideloadly', desc: 'Установка IPA с компьютера', url: 'https://sideloadly.io/', tags: ['ios'], os: ['w', 'm'] },
  { cat: 'android', name: 'AltStore', desc: 'Sideloading через AltServer', url: 'https://altstore.io/', tags: ['ios'], os: ['i'] },
  { cat: 'android', name: 'AppDB', desc: 'Каталог IPA и профилей', url: 'https://appdb.to/', tags: ['ios'], os: ['i'] },

  { cat: 'education', name: 'Coursera', desc: 'Курсы от университетов', url: 'https://www.coursera.org/', tags: ['courses', 'legal'], os: ['any'] },
  { cat: 'education', name: 'edX', desc: 'Онлайн-курсы MIT, Harvard и других', url: 'https://www.edx.org/', tags: ['courses', 'legal'], os: ['any'] },
  { cat: 'education', name: 'Khan Academy', desc: 'Бесплатное обучение с нуля', url: 'https://www.khanacademy.org/', tags: ['courses', 'legal'], os: ['any'] },
  { cat: 'education', name: 'MIT OCW', desc: 'Открытые курсы MIT', url: 'https://ocw.mit.edu/', tags: ['courses', 'legal'], os: ['any'] },
  { cat: 'education', name: 'freeCodeCamp', desc: 'Бесплатное обучение программированию', url: 'https://www.freecodecamp.org/', tags: ['courses', 'legal'], os: ['any'] },
  { cat: 'education', name: 'MDN Web Docs', desc: 'Документация по веб-технологиям', url: 'https://developer.mozilla.org/', tags: ['docs', 'legal'], os: ['any'] },
  { cat: 'education', name: 'Arch Wiki', desc: 'Linux-документация', url: 'https://wiki.archlinux.org/', tags: ['docs', 'legal'], os: ['any'] },
  { cat: 'education', name: 'CPPreference', desc: 'Справочник C и C++', url: 'https://en.cppreference.com/', tags: ['docs', 'legal'], os: ['any'] },
  { cat: 'education', name: 'Odysee', desc: 'Видео и документалистика', url: 'https://odysee.com/', tags: ['video'], os: ['any'] },
  { cat: 'education', name: 'Internet Archive', desc: 'Книги, видео, софт, веб-архив', url: 'https://archive.org/', tags: ['legal'], os: ['any'] },
  { cat: 'education', name: 'OSSU', desc: 'Открытый путь обучения Computer Science', url: 'https://github.com/ossu/computer-science', tags: ['courses', 'legal'], os: ['any'] },

  { cat: 'tools', name: 'Temp-Mail', desc: 'Временная почта', url: 'https://temp-mail.org/', tags: ['email'], os: ['any'] },
  { cat: 'tools', name: '10MinuteMail', desc: 'Одноразовая почта', url: 'https://10minutemail.com/', tags: ['email'], os: ['any'] },
  { cat: 'tools', name: 'Remove.bg', desc: 'Удаление фона с фото', url: 'https://www.remove.bg/', tags: ['image'], os: ['any'] },
  { cat: 'tools', name: 'Photopea', desc: 'Онлайн-аналог Photoshop', url: 'https://www.photopea.com/', tags: ['image', 'legal'], os: ['any'] },
  { cat: 'tools', name: 'Squoosh', desc: 'Сжатие изображений', url: 'https://squoosh.app/', tags: ['image', 'legal'], os: ['any'] },
  { cat: 'tools', name: 'TinyWow', desc: 'Набор онлайн-инструментов', url: 'https://tinywow.com/', tags: ['utils'], os: ['any'] },
  { cat: 'tools', name: 'Convertio', desc: 'Конвертация файлов', url: 'https://convertio.co/', tags: ['utils'], os: ['any'] },
  { cat: 'tools', name: 'JSON Crack', desc: 'Визуализация JSON', url: 'https://jsoncrack.com/', tags: ['dev'], os: ['any'] },
  { cat: 'tools', name: 'regex101', desc: 'Тестирование регулярных выражений', url: 'https://regex101.com/', tags: ['dev'], os: ['any'] },
  { cat: 'tools', name: 'Can I Use', desc: 'Поддержка веб-фич в браузерах', url: 'https://caniuse.com/', tags: ['dev'], os: ['any'] },
  { cat: 'tools', name: 'DownDetector', desc: 'Статус популярных сервисов', url: 'https://downdetector.com/', tags: ['utils'], os: ['any'] },
  { cat: 'tools', name: 'Speedtest', desc: 'Проверка скорости интернета', url: 'https://www.speedtest.net/', tags: ['utils'], os: ['any'] },
  { cat: 'tools', name: 'IPLeak', desc: 'Проверка утечек IP, DNS и WebRTC', url: 'https://ipleak.net/', tags: ['privacy'], os: ['any'] },
  { cat: 'tools', name: 'CyberChef', desc: 'Набор утилит для данных и кодировок', url: 'https://gchq.github.io/CyberChef/', tags: ['dev', 'utils'], os: ['any'] },
  { cat: 'tools', name: 'Excalidraw', desc: 'Быстрые схемы и наброски', url: 'https://excalidraw.com/', tags: ['utils'], os: ['any'] },

  { cat: 'download', name: 'MediaFire', desc: 'Файлообменник', url: 'https://www.mediafire.com/', tags: ['host'], os: ['any'] },
  { cat: 'download', name: 'Mega', desc: 'Облако с шифрованием', url: 'https://mega.nz/', tags: ['host'], os: ['any'] },
  { cat: 'download', name: 'Pixeldrain', desc: 'Быстрый файлообменник', url: 'https://pixeldrain.com/', tags: ['host'], os: ['any'] },
  { cat: 'download', name: 'Gofile', desc: 'Загрузка файлов без жёстких лимитов', url: 'https://gofile.io/', tags: ['host'], os: ['any'] },
  { cat: 'download', name: 'KrakenFiles', desc: 'Файлообменник', url: 'https://krakenfiles.com/', tags: ['host'], os: ['any'] },
  { cat: 'download', name: 'JDownloader', desc: 'Менеджер загрузок', url: 'https://jdownloader.org/', tags: ['client'], os: ['w', 'm', 'l'] },
  { cat: 'download', name: 'IDM', desc: 'Internet Download Manager', url: 'https://www.internetdownloadmanager.com/', tags: ['client'], os: ['w'] },
  { cat: 'download', name: 'AB Download Manager', desc: 'Современный менеджер загрузок', url: 'https://abdownloadmanager.com/', tags: ['client', 'os'], os: ['w'] },
  { cat: 'download', name: 'wget', desc: 'Консольная загрузка файлов', url: 'https://www.gnu.org/software/wget/', tags: ['client', 'os'], os: ['w', 'm', 'l'] },
  { cat: 'download', name: 'aria2', desc: 'Мощный консольный загрузчик', url: 'https://aria2.github.io/', tags: ['client', 'os'], os: ['w', 'm', 'l'] },
  { cat: 'download', name: 'Motrix', desc: 'GUI-загрузчик на базе aria2', url: 'https://motrix.app/', tags: ['client'], os: ['w', 'm', 'l'] }
];
